/**
 * One-off: turns the site's original hardcoded copy into an NDJSON file for
 * `sanity dataset import`. Kept in the repo as the record of what was seeded.
 *
 *   node scripts/generate-seed.mjs > seed.ndjson
 *   npx sanity dataset import seed.ndjson production
 *
 * Re-running the import creates DUPLICATES — document ids are generated by
 * Sanity (per schema guidance), so there is nothing to match on. Import once.
 */
import {LexoRank} from 'lexorank'

/** Sequential ranks matching the order of each list below. */
function ranker() {
  let rank = LexoRank.min()
  return () => {
    rank = rank.genNext()
    return rank.toString()
  }
}

const docs = []

/** Adds one document per item, ranked in array order. */
function addAll(type, items) {
  const next = ranker()
  for (const item of items) {
    docs.push({_type: type, orderRank: next(), ...item})
  }
}

docs.push({
  _id: 'siteSettings',
  _type: 'siteSettings',
  contactEmail: 'noerrtech@gmail.com',
  marqueeItems: [
    'React',
    'Next.js',
    'Remix',
    'Flutter',
    'Three.js',
    'GSAP',
    'Node',
    'NestJS',
    'PostgreSQL',
    'Prisma',
    'Supabase',
    'Firebase',
    'Razorpay',
    'Stripe',
    'OpenAI',
    'Tailwind',
  ],
})

addAll('project', [
  {
    name: 'RareSquare Studio',
    client: 'RareSquare',
    sector: 'Ecommerce',
    year: '2025',
    headline: 'Gifts as rare as the ones you love.',
    summary:
      'Personalised gifting storefront with a full commerce backend behind it — catalogue, cart, orders, payments and an admin panel, built as a monorepo so the storefront and dashboard ship independently.',
    stack: ['Turborepo', 'Prisma', 'PostgreSQL', 'Supabase', 'Razorpay', 'Firebase'],
    href: 'https://raresquare.web.app',
    mediaSlug: 'raresquare',
  },
  {
    name: 'Dermalicious',
    client: 'Dermalicious Clinic',
    sector: 'Healthcare',
    year: '2025',
    headline: 'Integrated multi-specialty healthcare.',
    summary:
      'A credibility-first clinic site for a practice where trust decides whether someone books. Server-rendered for search, with treatment structure and enquiry paths designed around how patients actually arrive.',
    stack: ['React Router', 'GSAP', 'SSR'],
    href: 'https://dermalicious-noerr.web.app',
    mediaSlug: 'dermalicious',
  },
  {
    name: 'South Mumbai United',
    client: 'South Mumbai United FC',
    sector: 'Sport',
    year: '2025',
    headline: 'The club, online.',
    summary:
      'Digital home for a Mumbai football club — squad, fixtures and club identity, built to hold up when matchday traffic spikes and the whole supporter base arrives at once.',
    stack: ['React', 'Firebase'],
    href: 'https://reactsmu.web.app',
    mediaSlug: 'south-mumbai-united',
  },
  {
    name: 'Tara Staycation',
    client: 'Tara Staycation',
    sector: 'Hospitality',
    year: '2025',
    headline: 'Somewhere worth staying.',
    summary:
      'Property and booking presence for a staycation brand, where the photography carries the sell and the enquiry path stays short enough that people finish it.',
    stack: ['React Router', 'Framer Motion', 'Tailwind'],
    href: 'https://tarastaycation.web.app',
    mediaSlug: 'tara-staycation',
  },
  {
    name: 'Rait Studio',
    client: 'Rait Studio',
    sector: 'Creative',
    year: '2025',
    headline: 'A studio that looks like one.',
    summary:
      'Portfolio platform for a creative studio — the work has to be the interface, so the layout gets out of the way and the imagery does the arguing.',
    stack: ['React Router', 'Tailwind'],
    href: 'https://rait-studio.web.app',
    mediaSlug: 'rait-studio',
  },
  {
    name: 'Krishnotsavam 2026',
    client: 'Procreate Experiences',
    sector: 'Live events',
    year: '2026',
    headline: 'Three nights, one celebration.',
    summary:
      "Launch site for a devotional music festival at Surat's Advaitaa Ballroom — three nights, three programmes, a lineup of artists and a live countdown to the doors opening. Scroll-led throughout, with everything bending toward the one action that matters: reserve a seat before the hall fills.",
    stack: ['Next.js', 'GSAP', 'Framer Motion', 'Tailwind', 'Firebase'],
    href: 'https://riya-krishna.web.app',
    mediaSlug: 'krishnotsavam',
  },
  {
    name: 'Neptune Container',
    client: 'Neptune Container Line & Logistics',
    sector: 'Shipping & logistics',
    year: '2025',
    headline: 'Move complex cargo across India and the world.',
    summary:
      'A logistics platform that has to read as institutionally solid — containerised, project and hazardous freight, twelve Indian branches, a global agent network. Motion-led marketing surface plus dedicated event microsites for Pacific Shipping Summit, Breakbulk Americas and TransportLogistics.',
    stack: ['React', 'Three.js', 'GSAP', 'Framer Motion', 'Tailwind'],
    href: 'https://neptune-containers.web.app',
    mediaSlug: 'neptune',
  },
])

addAll('shippedItem', [
  {name: 'Mystery Crate', sector: 'D2C · Mobile', stack: 'Flutter · Amplify · Next.js'},
  {name: 'Akshar Studio', sector: 'Creative tools', stack: 'Next.js · Three.js'},
  {name: 'FounderBrain', sector: 'AI · SaaS', stack: 'Next.js · OpenAI'},
  {name: 'Mumma Approved', sector: 'D2C content', stack: 'Next.js'},
  {name: 'JT Ecommerce', sector: 'Ecommerce', stack: 'Remix'},
  {name: 'Sportz Interactive', sector: 'Sport tech', stack: 'Full stack'},
  {name: 'Thakor Electronics', sector: 'Retail', stack: 'React'},
  {name: 'FlexHale Physio', sector: 'Healthcare', stack: 'React'},
  {name: 'Noerr Invoicing', sector: 'Internal tooling', stack: 'Next.js · PostgreSQL'},
])

addAll('capability', [
  {
    eyebrow: 'Interface',
    title: 'Product design',
    summary:
      'Identity, interface and motion design for products that have to feel considered on first open.',
    tools: ['UI systems', 'Design tokens', 'Motion', 'Prototypes'],
  },
  {
    eyebrow: 'Front of house',
    title: 'Web platforms',
    summary:
      'Marketing sites and full applications, server-rendered where it matters for speed and search.',
    tools: ['Next.js', 'Remix', 'React Router', 'Tailwind', 'Three.js', 'GSAP'],
  },
  {
    eyebrow: 'In hand',
    title: 'Mobile',
    summary: 'Cross-platform apps shipped to both stores, sharing one backend with the web product.',
    tools: ['Flutter', 'Amplify', 'Push & auth'],
  },
  {
    eyebrow: 'Underneath',
    title: 'Backend & data',
    summary:
      'APIs, schemas and the boring reliability work — the part that decides whether launch holds.',
    tools: ['Node', 'NestJS', 'Express', 'PostgreSQL', 'Prisma', 'Supabase', 'Firebase'],
  },
  {
    eyebrow: 'Money',
    title: 'Commerce & payments',
    summary:
      'Checkout, subscriptions and invoicing wired to real gateways, tested against real edge cases.',
    tools: ['Razorpay', 'Stripe', 'Sanity', 'Invoicing'],
  },
  {
    eyebrow: 'New',
    title: 'AI features',
    summary:
      'Model-backed features built into products — transcription, extraction, generation — not bolted on as a demo.',
    tools: ['OpenAI', 'Voice capture', 'Structured output'],
  },
])

addAll('methodStep', [
  {
    eyebrow: 'Draft one',
    title: 'Define',
    summary:
      'What the product owes its user, and the shortest route there. Scope gets cut here, not mid-build.',
    state: 'draft',
  },
  {
    eyebrow: 'Draft two',
    title: 'Design',
    summary:
      'Interface and system in one pass, in the browser early, so what you approve is what runs.',
    state: 'draft',
  },
  {
    eyebrow: 'Draft three',
    title: 'Build',
    summary:
      'Typed, reviewed, deployed on a real pipeline — with the backend built by the same people.',
    state: 'draft',
  },
  {
    eyebrow: 'Resolved',
    title: 'Hold',
    summary:
      'We stay on after launch. Monitoring, fixes, the next release — the version that ships clean stays clean.',
    state: 'resolved',
  },
])

addAll('stat', [
  {value: '30+', label: 'Products shipped'},
  {value: '9', label: 'Industries'},
  {value: '6', label: 'Live platforms maintained'},
  {value: '1', label: 'Team, end to end'},
])

addAll('testimonial', [
  {
    status: 'placeholder',
    quote:
      "We came in with a half-finished build and a launch date we couldn't move. They took the whole thing over, shipped in five weeks, and it hasn't gone down since.",
    metric: 'Live in 5 weeks',
    name: 'Priya Raghavan',
    role: 'Founder',
    company: 'Kestrel & Co',
    initials: 'PR',
  },
  {
    status: 'placeholder',
    quote:
      'Checkout was losing us orders and nobody could tell us why. They found it in two days and rebuilt the flow properly.',
    metric: 'Conversion 1.4% → 3.9%',
    name: 'Daniel Okoye',
    role: 'Head of Ecommerce',
    company: 'Northbay Supply',
    initials: 'DO',
  },
  {
    status: 'placeholder',
    quote:
      "The only team we've worked with that actually stayed after launch. Two years on, they still ship every release for us.",
    metric: '2 years, still shipping',
    name: 'Meera Shah',
    role: 'Chief Operating Officer',
    company: 'Lantern Health',
    initials: 'MS',
  },
])

addAll('contactFact', [
  {label: 'Response', value: 'Within 2 working days'},
  {label: 'Engagements', value: 'Project · Retainer'},
  {label: 'Based', value: 'Mumbai, India'},
  {label: 'Working with', value: 'India · US · UK'},
])

addAll('navLink', [
  {name: 'Work', href: '#work', variant: 'text'},
  {name: 'Capabilities', href: '#capabilities', variant: 'text'},
  {name: 'Method', href: '#method', variant: 'text'},
  {name: 'Start a project', href: '#contact', variant: 'button'},
])

for (const doc of docs) console.log(JSON.stringify(doc))
